### ISSUE TITLE
AboutEval

### ISSUE THREAD

**Issue by zhangyanide** [rohanchandra30/Spectral-Trajectory-and-Behavior-Prediction#21] opened 2020-03-25 07:13 UTC
why i  change the variable TRAIN False, The APOL mode's ADE is 3. and the ARGO mode, LYFT mode can't run

**Comment by rohanchandra30** [comment] 2020-03-25 16:34
Can you post the error message?

**Comment by rohanchandra30** [comment] 2020-03-30 02:20
Closing this out. Feel free to open it again if problem persists.

**Comment by zhangyanide** [comment] 2020-03-30 07:11
When i set the TRAIN is false, ARGO mode and LYFT mode can't run
the erro message:
ValueError: array must not contain infs or NaNs

**Comment by rohanchandra30** [comment] 2020-03-30 17:09
Does it go through the both TRAIN and EVAL stages when you set both TRAIN and EVAL to true?

**Comment by zhangyanide** [comment] 2020-03-31 03:47
Thanks for your help, i run the results for three modes. However, the result of ADE and FDE is high, Did i miss something?
The setting and results as fowllow:

# DATA = 'APOL'
# train_seq_len = 6
# pred_seq_len = 10

# DATA = 'LYFT'
# train_seq_len = 20
# pred_seq_len = 30

DATA = 'ARGO'
train_seq_len = 20
pred_seq_len = 30

device = torch.device("cuda")
 s2 = True
TRAIN = False
EVAL = True
DIR = '../resources/data/{}/'.format(DATA)
MODEL_DIR = '../resources/trained_models/'
epochs = 15
save_per_epochs = 5

The result of APOL:

![APOL](https://user-images.githubusercontent.com/38414155/77984803-2e015b80-7345-11ea-8f3d-3a66bbbb7029.png)

**Comment by rohanchandra30** [comment] 2020-03-31 04:16
No your code is fine.

The current code no longer reproduces the results in the paper due to some modifications and adjustments made to the code. There were some other modifications as well.

Consequently, we are expecting to update the paper with new results. Things have become a little delayed due to the coronavirus situation, unfortunately !

**Comment by zhangyanide** [comment] 2020-03-31 05:29
Thank you, and take care of yourself

**Comment by rohanchandra30** [comment] 2020-03-31 05:41
you too, stay safe. We will notify once we update the repository with new results !

**Closed by rohanchandra30** 2020-03-31 05:41 UTC
Labels: question

**Comment by CuttlefishXuan** [comment] 2020-05-07 10:10
Hi, @zhangyanide 
Can I ask u about the reaults of the GRIP model? I tested the GRIP model on ARGO and LYFT datasets, and the ADE/FDE is about 30. I don't know if there is something wrong with my code?

**Comment by zhangyanide** [comment] 2020-05-12 01:13
> Hi, @zhangyanide
> Can I ask u about the reaults of the GRIP model? I tested the GRIP model on ARGO and LYFT datasets, and the ADE/FDE is about 30. I don't know if there is something wrong with my code?

Sorry, I 'm not focus on the GRIP model. Maybe you can ask for the author
